name: BiliLive

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.actor }}/bililive:1.0
  
  push:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to GitHub Container Registry
      - uses: docker/login-action@v2
      - with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
<<<<<<< HEAD
      - run: docker push ghcr.io/${{ github.actor }}/bililive:1.0
=======
      - name: Push image to Github
        run: docker push ghcr.io/${{ github.actor }}/bililive:1.0
>>>>>>> 0ce1f30 (Action)
